# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [5]:
# Create a 1-dimensional NumPy array using np.array()
array1D = np.array([1,5,7,5])

# Create a 2-dimensional NumPy array using np.array()
array2D = np.array([[1,5,7,5],
                   [1,5,7,5]])

# Create a 3-dimensional Numpy array using np.array()
array3D = np.array([[[2,2],[3,3]],
                   [[4,4],[5,5]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [13]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(array1D.shape)
print(array1D.ndim)
print(array1D.dtype)
print(array1D.size)

(4,)
1
int32
4


In [14]:
# Attributes of 2-dimensional array
print(array2D.shape)
print(array2D.ndim)
print(array2D.dtype)
print(array2D.size)

(2, 4)
2
int32
8


In [15]:
# Attributes of 3-dimensional array
print(array3D.shape)
print(array3D.ndim)
print(array3D.dtype)
print(array3D.size)

(2, 2, 2)
3
int32
8


In [16]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(array2D)

In [17]:
# Create an array of shape (10, 2) with only ones
ones_array = np.ones((10,2))

In [18]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_arr = np.zeros((7,2,3))

In [19]:
# Create an array within a range of 0 and 100 with step 3
stp3_arr = np.arange(0, 100, 3)

In [24]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rand_arr = np.random.randint(0, 11, size=(7,2))

In [25]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
flts_arr = np.random.rand(3, 5)

In [38]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arr = np.random.randint(0,11, size=(4,6))
print(arr)

[[ 6  3 10  7  4  6]
 [ 9  2  6 10 10  7]
 [ 4  3  7  7  2  5]
 [ 4  1  7  5  1  4]]


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [42]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
var = np.random.randint(1,11, size=(3,7))

# Find the unique numbers in the array you just created
unique = np.unique(var)
print(unique)


[ 1  2  3  5  7  8  9 10]


In [43]:
# Find the 0'th index of the latest array you created
ind0 = var[0][0]
print(ind0)

8


In [44]:
# Get the first 2 rows of latest array you created
print(var[:2])

[[ 8  8  3  1  8  3  3]
 [ 1  5 10  7 10  9  7]]


In [45]:
# Get the first 2 values of the first 2 rows of the latest array
print(var[:2, :2])

[[8 8]
 [1 5]]


In [47]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
randoms = np.random.randint(0,11, size=(3,5))
ones = np.ones((3,5))

In [48]:
# Add the two arrays together
added_arrays = randoms + ones
print(added_arrays)


[[11.  9. 10. 10.  3.]
 [ 7.  1.  4.  4.  5.]
 [ 7.  7. 11.  4.  7.]]


In [49]:
# Create another array of ones of shape (5, 3)
ones2 = np.ones((5,3))

In [51]:
# Try add the array of ones and the other most recent array together
added_arrays2 = added_arrays + ones2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [53]:
# Create another array of ones of shape (3, 5)
ones3 = np.ones((3,5))

In [58]:
# Subtract the new array of ones from the other most recent array
sub = added_arrays - ones3
print(sub)

[[10.  8.  9.  9.  2.]
 [ 6.  0.  3.  3.  4.]
 [ 6.  6. 10.  3.  6.]]


In [66]:
# Multiply the ones array with the latest array
multp = sub * ones3
print(multp)

[[10.  8.  9.  9.  2.]
 [ 6.  0.  3.  3.  4.]
 [ 6.  6. 10.  3.  6.]]


In [67]:
# Take the latest array to the power of 2 using '**'
multp_powered = multp**2
print(multp_powered)

[[100.  64.  81.  81.   4.]
 [ 36.   0.   9.   9.  16.]
 [ 36.  36. 100.   9.  36.]]


In [71]:
# Do the same thing with np.square()
multp_powered2 = np.square(multp)
print(multp_powered2)

[[100.  64.  81.  81.   4.]
 [ 36.   0.   9.   9.  16.]
 [ 36.  36. 100.   9.  36.]]


In [73]:
# Find the mean of the latest array using np.mean()
meann = np.mean(multp_powered2)
print(meann)

41.13333333333333


In [76]:
# Find the maximum of the latest array using np.max()
maxx = np.max(multp_powered2)
print(maxx)

100.0


In [77]:
# Find the minimum of the latest array using np.min()
minn = np.min(multp_powered2)
print(minn)

0.0


In [78]:
# Find the standard deviation of the latest array
std = np.std(multp_powered2)
print(std)

34.19330668745307


In [79]:
# Find the variance of the latest array
variance = np.var(multp_powered2)
print(variance)

1169.1822222222224


In [81]:
# Reshape the latest array to (3, 5, 1)
reshaped = np.reshape(multp_powered2, (3,5,1))
print(reshaped)

[[[100.]
  [ 64.]
  [ 81.]
  [ 81.]
  [  4.]]

 [[ 36.]
  [  0.]
  [  9.]
  [  9.]
  [ 16.]]

 [[ 36.]
  [ 36.]
  [100.]
  [  9.]
  [ 36.]]]


In [82]:
# Transpose the latest array
transposed = np.transpose(multp_powered2)
print(transposed)

[[100.  36.  36.]
 [ 64.   0.  36.]
 [ 81.   9. 100.]
 [ 81.   9.   9.]
 [  4.  16.  36.]]


What does the transpose do?

In [84]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
first = np.random.randint(0,11, size=(3,3))
second = np.random.randint(0,11, size=(3,2))
print(first)
print(second)

[[10  2  5]
 [ 1  9  8]
 [ 4  5  3]]
[[10  9]
 [ 6  8]
 [ 6  0]]


In [86]:
# Perform a dot product on the two newest arrays you created
dot = np.dot(first, second)
print(dot)

[[142 106]
 [112  81]
 [ 88  76]]


In [87]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
first = np.random.randint(0,11, size=(4,3))
second = np.random.randint(0,11, size=(4,3))

In [88]:
# Perform a dot product on the two newest arrays you created
dot = np.dot(first, second)


ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [91]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
trans = np.transpose(first)
dot = np.dot(trans, second) 
print(dot)

[[103  70  96]
 [119  63  94]
 [161  91 140]]


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [101]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
np.random.seed(42)
first = np.random.randint(0,11, size=(4,3))
second = np.random.randint(0,11, size=(4,3))
print(first)
print(second)

[[ 6  3 10]
 [ 7  4  6]
 [ 9  2  6]
 [10 10  7]]
[[4 3 7]
 [7 2 5]
 [4 1 7]
 [5 1 4]]


In [102]:
# Compare the two arrays with '>'
greater = np.greater(first,second)
print(greater)

[[ True False  True]
 [False  True  True]
 [ True  True False]
 [ True  True  True]]


What happens when you compare the arrays with `>`?

In [103]:
# Compare the two arrays with '>='
greater_or_equal = np.greater_equal(first,second)
print(greater_or_equal)

[[ True  True  True]
 [ True  True  True]
 [ True  True False]
 [ True  True  True]]


In [105]:
# Find which elements of the first array are greater than 7
greater7 = np.where(first > 7)
print(first[greater7])

[10  9 10 10]


In [106]:
# Which parts of each array are equal? (try using '==')
equall = np.equal(first,second)
print(equall)

[[False  True False]
 [ True False False]
 [False False False]
 [False False False]]


In [108]:
# Sort one of the arrays you just created in ascending order
sortedd = np.sort(first)
print(sortedd)

[[ 3  6 10]
 [ 4  6  7]
 [ 2  6  9]
 [ 7 10 10]]


In [109]:
# Sort the indexes of one of the arrays you just created
indx_sorted = np.argsort(first)
print(indx_sorted)


[[1 0 2]
 [1 2 0]
 [1 2 0]
 [2 0 1]]


In [110]:
# Find the index with the maximum value in one of the arrays you've created
ixd_max = np.argmax(first)
print(ixd_max)

2


In [111]:
# Find the index with the minimum value in one of the arrays you've created
ixd_min = np.argmin(first)
print(ixd_min)

7


In [112]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
ixds_max = np.argmax(first, axis=1)
print(ixds_max)     

[2 0 0 0]


In [113]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
indxs_min = np.argmin(first, axis=0)
print(indxs_min)

[0 2 1]


In [114]:
# Create an array of normally distributed random numbers
arr = np.random.normal(size=(3, 5))
print(arr)

[[ 1.46237812  1.53871497 -2.43910582  0.60344123 -0.25104397]
 [-0.16386712 -1.47632969  1.48698096 -0.02445518  0.35555132]
 [ 0.41701111  0.83246186 -0.29339915 -0.02983857  0.09512578]]


In [115]:
# Create an array with 10 evenly spaced numbers between 1 and 100
arr = np.linspace(1, 100, num=10)
print(arr)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.